[deps]
BasicInterpolators = "26cce99e-4866-4b6d-ab74-862489e035e0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExtractMacro = "f86d3d12-fd5b-522c-99e9-61577282a1e9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
